/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LoginVendedorController;
import controller.ProdutoController;
import java.io.File;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import model.Produto;
import util.Utils;

/**
 *
 * @author aluno.saolucas
 */
public class FrAdicionarProduto extends javax.swing.JDialog {

    /**
     * Creates new form FrAdicionarProduto
     */
    public FrAdicionarProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbVoltar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        imgFoto = new javax.swing.JLabel();
        btnVincularImagem = new javax.swing.JButton();
        edtNomeProduto = new javax.swing.JTextField();
        edtEstoque = new javax.swing.JTextField();
        edtValorProduto = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnAdicionarProduto = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 234, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(41, 89, 134));

        jPanel3.setBackground(new java.awt.Color(35, 69, 108));

        lbVoltar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbVoltar.setForeground(new java.awt.Color(255, 255, 255));
        lbVoltar.setText("Voltar");
        lbVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbVoltar)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Adicionar produto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 635, -1));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 152, 90, -1));

        btnVincularImagem.setText("Vincular imagem");
        btnVincularImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVincularImagemMouseClicked(evt);
            }
        });
        btnVincularImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVincularImagemActionPerformed(evt);
            }
        });
        jPanel1.add(btnVincularImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 185, -1, -1));

        edtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(edtNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 300, 154, -1));
        jPanel1.add(edtEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 364, 85, -1));
        jPanel1.add(edtValorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 432, 154, -1));

        btnLimpar.setText("limpar");
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        btnAdicionarProduto.setText("adicionar");
        btnAdicionarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdicionarProdutoMouseClicked(evt);
            }
        });
        jPanel1.add(btnAdicionarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        jPanel5.setBackground(new java.awt.Color(35, 69, 108));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sobre");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(564, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 491, 635, 40));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome do produto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 278, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Valor do produto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 410, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Estoque");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 342, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeProdutoActionPerformed

    private void btnAdicionarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoMouseClicked
        cadastrarProduto();
    }//GEN-LAST:event_btnAdicionarProdutoMouseClicked

    private void lbVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbVoltarMouseClicked
        FrTelaInicialVendedor telaInicial = new FrTelaInicialVendedor();
        dispose();
        telaInicial.setVisible(true);
    }//GEN-LAST:event_lbVoltarMouseClicked

    private void btnVincularImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVincularImagemMouseClicked
        //escolher a imagem
        File arquivo = Utils.escolherImagem();

        //carrega a imagem se selecionou um arquivo
        if (arquivo != null) {
            //Converte para um ícone
            Icon icone = Utils.converterFileToIcon(arquivo);

            //redimensiono a imagem para caber no imgFoto
            Icon iconeNovo = Utils.redimensionarImagem(icone, 110, 100);

            imgFoto.setIcon(iconeNovo);
        }

    }//GEN-LAST:event_btnVincularImagemMouseClicked

    private void btnVincularImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVincularImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVincularImagemActionPerformed

   
    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        edtNomeProduto.setText("");
        edtEstoque.setText("");
        edtValorProduto.setText("");

    }//GEN-LAST:event_btnLimparMouseClicked

    private boolean verificarCampos() {
        if (edtNomeProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nome do produto em branco");
            return false;
        }
        if (edtEstoque.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Estoque do produto em branco");
            return false;
        }
        if (edtValorProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Valor do produto em branco");
            return false;
        }
        return true;
    }

    private void cadastrarProduto() {

        if (!verificarCampos()) {
            return;
        }
        //Ler os campos
        String nome = edtNomeProduto.getText();
        int estoque = Integer.parseInt(edtEstoque.getText());
        double preco = Double.parseDouble(edtValorProduto.getText());

        Produto produto = new Produto();
        produto.setNome(nome);
        produto.setEstoque(estoque);
        produto.setPreco(preco);
        produto.setImagem(imgFoto.getIcon());

        ProdutoController controller = new ProdutoController();

        if (controller.inserir(produto)) {
            JOptionPane.showMessageDialog(rootPane, "Produto inserido");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos obrigatórios");
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAdicionarProduto dialog = new FrAdicionarProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProduto;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVincularImagem;
    private javax.swing.JTextField edtEstoque;
    private javax.swing.JTextField edtNomeProduto;
    private javax.swing.JTextField edtValorProduto;
    private javax.swing.JLabel imgFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbVoltar;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
