/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProdutoController;
import java.util.List;
import model.Produto;

/**
 *
 * @author aluno.saolucas
 */
public class FrCarrinho extends javax.swing.JFrame {

    /**
     * Creates new form FrCarrinho
     */
    public FrCarrinho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbVoltar = new javax.swing.JLabel();
        lbRetornar = new javax.swing.JLabel();
        lbProxima = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbFoto1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbFoto2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbFoto3 = new javax.swing.JLabel();
        lbPreco3 = new javax.swing.JLabel();
        lbPreco1 = new javax.swing.JLabel();
        lbPreco2 = new javax.swing.JLabel();
        lbValorTotal = new javax.swing.JLabel();
        btnExecutarCompra = new javax.swing.JButton();
        btnRemover1 = new javax.swing.JButton();
        btnRemover2 = new javax.swing.JButton();
        btnRemover3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbNome1 = new javax.swing.JLabel();
        lbNome2 = new javax.swing.JLabel();
        lbNome3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlPrincipal.setBackground(new java.awt.Color(234, 234, 234));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(41, 89, 134));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seu carrinho");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(380, 380, 380))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
        );

        pnlPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        jPanel3.setBackground(new java.awt.Color(35, 69, 108));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        lbVoltar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbVoltar.setForeground(new java.awt.Color(255, 255, 255));
        lbVoltar.setText("Voltar");
        lbVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbVoltarMouseClicked(evt);
            }
        });

        lbRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/seta24.png"))); // NOI18N

        lbProxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/seta24.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                .addComponent(lbRetornar)
                .addGap(18, 18, 18)
                .addComponent(lbProxima)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbProxima)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbVoltar)
                        .addComponent(lbRetornar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPrincipal.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 620, -1));

        jPanel2.setBackground(new java.awt.Color(35, 69, 108));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sobre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(553, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 620, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFoto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFoto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pnlPrincipal.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFoto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFoto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pnlPrincipal.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFoto3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFoto3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pnlPrincipal.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        lbPreco3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPreco3.setForeground(new java.awt.Color(0, 0, 0));
        lbPreco3.setText("R$ ----");
        pnlPrincipal.add(lbPreco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, -1, -1));

        lbPreco1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPreco1.setForeground(new java.awt.Color(0, 0, 0));
        lbPreco1.setText("R$ ----");
        pnlPrincipal.add(lbPreco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        lbPreco2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPreco2.setForeground(new java.awt.Color(0, 0, 0));
        lbPreco2.setText("R$ ----");
        pnlPrincipal.add(lbPreco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        lbValorTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbValorTotal.setForeground(new java.awt.Color(0, 0, 0));
        lbValorTotal.setText("Valor Total: ");
        pnlPrincipal.add(lbValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, -1));

        btnExecutarCompra.setText("Executar Compra");
        btnExecutarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExecutarCompraMouseClicked(evt);
            }
        });
        pnlPrincipal.add(btnExecutarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, -1, -1));

        btnRemover1.setText("Remover");
        pnlPrincipal.add(btnRemover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        btnRemover2.setText("Remover");
        pnlPrincipal.add(btnRemover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        btnRemover3.setText("Remover");
        pnlPrincipal.add(btnRemover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("0");
        pnlPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, -1, -1));

        lbNome1.setForeground(new java.awt.Color(0, 0, 0));
        lbNome1.setText("Nome");
        pnlPrincipal.add(lbNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        lbNome2.setForeground(new java.awt.Color(0, 0, 0));
        lbNome2.setText("Nome");
        pnlPrincipal.add(lbNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        lbNome3.setForeground(new java.awt.Color(0, 0, 0));
        lbNome3.setText("Nome");
        pnlPrincipal.add(lbNome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbVoltarMouseClicked
        frMenu frmenu = new frMenu();
        dispose();
        frmenu.setVisible(true);
    }//GEN-LAST:event_lbVoltarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnExecutarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExecutarCompraMouseClicked
        FrPagamento frpagamento = new FrPagamento(null, rootPaneCheckingEnabled);
        dispose();
        frpagamento.setVisible(true);
    }//GEN-LAST:event_btnExecutarCompraMouseClicked

    public void consultarProdutosCarrinho(){
    ProdutoController controller = new ProdutoController();
    
    Produto produto = new Produto();

        lbNome1.setText(produto.getNome());
        produto.getEstoque();
        lbPreco1.setText("R$" + String.valueOf(produto.getPreco()));
        lbFoto1.setIcon(produto.getImagem());
        
    }
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCarrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecutarCompra;
    private javax.swing.JButton btnRemover1;
    private javax.swing.JButton btnRemover2;
    private javax.swing.JButton btnRemover3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbFoto1;
    private javax.swing.JLabel lbFoto2;
    private javax.swing.JLabel lbFoto3;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbNome2;
    private javax.swing.JLabel lbNome3;
    private javax.swing.JLabel lbPreco1;
    private javax.swing.JLabel lbPreco2;
    private javax.swing.JLabel lbPreco3;
    private javax.swing.JLabel lbProxima;
    private javax.swing.JLabel lbRetornar;
    private javax.swing.JLabel lbValorTotal;
    private javax.swing.JLabel lbVoltar;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
