/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProdutoController;
import controller.VendaController;
import java.util.List;
import model.Produto;

/**
 *
 * @author aluno.saolucas
 */
public class frComputadores extends javax.swing.JFrame {

    private int pagina = 1;

    public frComputadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbCarrinho = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filtro = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        pnlProd2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbProduto2 = new javax.swing.JLabel();
        btnComprar2 = new javax.swing.JButton();
        lbPreco2 = new javax.swing.JLabel();
        lbNome2 = new javax.swing.JLabel();
        pnlProd3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lbProduto3 = new javax.swing.JLabel();
        btnComprar3 = new javax.swing.JButton();
        lbPreco3 = new javax.swing.JLabel();
        lbNome3 = new javax.swing.JLabel();
        pnlProd1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lbProduto1 = new javax.swing.JLabel();
        btnComprar1 = new javax.swing.JButton();
        lbPreco1 = new javax.swing.JLabel();
        lbNome1 = new javax.swing.JLabel();
        btnProxima = new javax.swing.JButton();
        lbPagina = new javax.swing.JLabel();
        btnRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(234, 234, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(41, 89, 134));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tela computadores");

        jTextField1.setText("Pesquisar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 100));

        jPanel3.setBackground(new java.awt.Color(35, 69, 108));

        lbCarrinho.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        lbCarrinho.setText("Seu Carrinho");
        lbCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCarrinhoMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Voltar");

        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hd", "Ssd", "Memória", "Processador", "Fonte" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(251, 251, 251)
                .addComponent(lbCarrinho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCarrinho)
                    .addComponent(jLabel2)
                    .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 760, 40));

        jPanel5.setBackground(new java.awt.Color(35, 69, 108));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Sobre");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(694, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 760, -1));

        pnlProd2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbProduto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbProduto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        btnComprar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/shop.png"))); // NOI18N
        btnComprar2.setText("Comprar");

        lbPreco2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPreco2.setForeground(new java.awt.Color(0, 0, 0));
        lbPreco2.setText("R$");

        lbNome2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbNome2.setForeground(new java.awt.Color(0, 0, 0));
        lbNome2.setText("Nome");

        javax.swing.GroupLayout pnlProd2Layout = new javax.swing.GroupLayout(pnlProd2);
        pnlProd2.setLayout(pnlProd2Layout);
        pnlProd2Layout.setHorizontalGroup(
            pnlProd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProd2Layout.createSequentialGroup()
                .addGroup(pnlProd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProd2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlProd2Layout.createSequentialGroup()
                        .addGroup(pnlProd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProd2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnComprar2))
                            .addGroup(pnlProd2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(pnlProd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNome2)
                                    .addComponent(lbPreco2))))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlProd2Layout.setVerticalGroup(
            pnlProd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProd2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbPreco2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnComprar2)
                .addContainerGap())
        );

        jPanel1.add(pnlProd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 200, 270));

        pnlProd3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbProduto3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbProduto3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        btnComprar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/shop.png"))); // NOI18N
        btnComprar3.setText("Comprar");

        lbPreco3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPreco3.setForeground(new java.awt.Color(0, 0, 0));
        lbPreco3.setText("R$");

        lbNome3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbNome3.setForeground(new java.awt.Color(0, 0, 0));
        lbNome3.setText("Nome");

        javax.swing.GroupLayout pnlProd3Layout = new javax.swing.GroupLayout(pnlProd3);
        pnlProd3.setLayout(pnlProd3Layout);
        pnlProd3Layout.setHorizontalGroup(
            pnlProd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProd3Layout.createSequentialGroup()
                .addGroup(pnlProd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProd3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlProd3Layout.createSequentialGroup()
                        .addGroup(pnlProd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProd3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnComprar3))
                            .addGroup(pnlProd3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(pnlProd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNome3)
                                    .addComponent(lbPreco3))))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlProd3Layout.setVerticalGroup(
            pnlProd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProd3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(lbPreco3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNome3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnComprar3)
                .addContainerGap())
        );

        jPanel11.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(pnlProd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 200, 270));

        pnlProd1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbProduto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbProduto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnComprar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/shop.png"))); // NOI18N
        btnComprar1.setText("Comprar");
        btnComprar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprar1MouseClicked(evt);
            }
        });

        lbPreco1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPreco1.setForeground(new java.awt.Color(0, 0, 0));
        lbPreco1.setText("R$10");

        lbNome1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbNome1.setForeground(new java.awt.Color(0, 0, 0));
        lbNome1.setText("Nome");

        javax.swing.GroupLayout pnlProd1Layout = new javax.swing.GroupLayout(pnlProd1);
        pnlProd1.setLayout(pnlProd1Layout);
        pnlProd1Layout.setHorizontalGroup(
            pnlProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProd1Layout.createSequentialGroup()
                .addGroup(pnlProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProd1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlProd1Layout.createSequentialGroup()
                        .addGroup(pnlProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProd1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnComprar1))
                            .addGroup(pnlProd1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(pnlProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNome1)
                                    .addComponent(lbPreco1))))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlProd1Layout.setVerticalGroup(
            pnlProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProd1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbPreco1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnComprar1)
                .addContainerGap())
        );

        jPanel1.add(pnlProd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 200, 270));

        btnProxima.setText("Próxima página");
        btnProxima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProximaMouseClicked(evt);
            }
        });
        jPanel1.add(btnProxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, -1, -1));

        lbPagina.setForeground(new java.awt.Color(0, 0, 0));
        lbPagina.setText("Página 1");
        jPanel1.add(lbPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        btnRetornar.setText("Retornar");
        btnRetornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetornarMouseClicked(evt);
            }
        });
        jPanel1.add(btnRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void lbCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCarrinhoMouseClicked
        FrCarrinho frcarrinho = new FrCarrinho();
        dispose();
        frcarrinho.setVisible(true);
    }//GEN-LAST:event_lbCarrinhoMouseClicked

    private void btnProximaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProximaMouseClicked
        pagina++;

        if (pagina > 1) {
            btnRetornar.setVisible(true);

        }

        navegacaoPaginas();
        buscarProdutos(pagina);


    }//GEN-LAST:event_btnProximaMouseClicked

    private void btnRetornarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetornarMouseClicked
        pagina--;

        if (pagina == 1) {
            btnRetornar.setVisible(false);
        }

        navegacaoPaginas();
        buscarProdutos(pagina);

    }//GEN-LAST:event_btnRetornarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        buscarProdutos(pagina);
    }//GEN-LAST:event_formWindowOpened

    private void btnComprar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar1MouseClicked
        VendaController vendaController = new VendaController();
        


    }//GEN-LAST:event_btnComprar1MouseClicked

    public void navegacaoPaginas() {
        lbPagina.setText("Página " + pagina);
    }

    public void buscarProdutos(int pagina) {

        int offset = (pagina * 3) - 3;

        ProdutoController controller = new ProdutoController();

        List<Produto> lista = controller.consultar(offset);

        Produto produto;

        int tamanho = lista.size();
        if (tamanho >= 1) {
            pnlProd1.setVisible(true);

            produto = lista.get(0);

            if (produto != null) {
                lbNome1.setText(produto.getNome());
                produto.getEstoque();
                lbPreco1.setText("R$" + String.valueOf(produto.getPreco()));
                lbProduto1.setIcon(produto.getImagem());
            }
        } else {
            pnlProd1.setVisible(false);
        }

        if (tamanho >= 2) {
            pnlProd2.setVisible(true);
            produto = lista.get(1);

            if (produto != null) {
                lbNome2.setText(produto.getNome());
                produto.getEstoque();
                lbPreco2.setText("R$" + String.valueOf(produto.getPreco()));
                lbProduto2.setIcon(produto.getImagem());
            }

        } else {
            pnlProd2.setVisible(false);
        }

        if (tamanho >= 3) {
            pnlProd3.setVisible(true);
            produto = lista.get(2);

            if (produto != null) {
                lbNome3.setText(produto.getNome());
                produto.getEstoque();
                lbPreco3.setText("R$" + String.valueOf(produto.getPreco()));
                lbProduto3.setIcon(produto.getImagem());
            }
        } else {
            pnlProd3.setVisible(false);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frComputadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar1;
    private javax.swing.JButton btnComprar2;
    private javax.swing.JButton btnComprar3;
    private javax.swing.JButton btnProxima;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbCarrinho;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbNome2;
    private javax.swing.JLabel lbNome3;
    private javax.swing.JLabel lbPagina;
    private javax.swing.JLabel lbPreco1;
    private javax.swing.JLabel lbPreco2;
    private javax.swing.JLabel lbPreco3;
    private javax.swing.JLabel lbProduto1;
    private javax.swing.JLabel lbProduto2;
    private javax.swing.JLabel lbProduto3;
    private javax.swing.JPanel pnlProd1;
    private javax.swing.JPanel pnlProd2;
    private javax.swing.JPanel pnlProd3;
    // End of variables declaration//GEN-END:variables

}
